version: 0.1.{build}
max_jobs: 4
image: Visual Studio 2017

matrix:
    fast_finish: true

platform:
    - x86
    - x64
configuration:
    - Release
    - Debug

environment:
    NINJA_DIR: C:\Tools\ninja
    GENERATOR: Ninja
    VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'

cache: c:\tools\vcpkg\installed\

install:
    - if not exist %NINJA_DIR%\ mkdir %NINJA_DIR%
    - cd %NINJA_DIR%
    - if not exist ninja.exe appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
    - if not exist ninja.exe 7z x ninja-win.zip
    - set PATH=%NINJA_DIR%;%PATH%
    - vcpkg install gtest:%PLATFORM%-windows
    - vcpkg integrate install

build_script:
    - call "%VCVARSALL%" %PLATFORM%
    - cd %APPVEYOR_BUILD_FOLDER%
    - cmake -G "%GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=%PLATFORM%-windows -DBUILD_TESTS=ON .
    - cmake --build . --config %CONFIGURATION%
    - ctest -C %CONFIGURATION% -V
