language: cpp
dist: trusty
sudo: false

cache: ccache

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libgtest-dev

install:
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir ~/gtest
    - cp -r /usr/src/gtest/. ~/gtest
    - cd ~/gtest
    - cmake .
    - make
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/gtest
    - export LD_LIBRARY_PATH
    - LIBRARY_PATH=$LIBRARY_PATH:~/gtest
    - export LIBRARY_PATH
    - ls -la



script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test
