language: cpp
dist: trusty
sudo: required

cache: ccache

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libgtest-dev

before_script:
    - export CC=gcc-7
    - export CXX=g++-7

script:
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd $TRAVIS_BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test
