language: cpp
dist: trusty
sudo: false

cache: ccache

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libgtest-dev

install:
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir ~/gtest
    - cp -r /usr/src/gtest/. ~/gtest
    - cd ~/gtest
    - cmake .
    - make
    - ln -s $(pwd)/libgtest.a /usr/lib/libgtest.a 
    - ln -s $(pwd)/libgtest_main.a /usr/lib/libgtest_main.a

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test
