language: cpp
dist: trusty
sudo: false

cache: ccache

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libgtest-dev
            - lcov
            - gcovr

install:
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir ~/gtest
    - cp -r /usr/src/gtest/. ~/gtest
    - cd ~/gtest
    - cmake .
    - make
    - export GTEST_ROOT=$(pwd)

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCOVERAGE=ON .
    - make
    - make BattleSystem_coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
