language: cpp
dist: trusty
sudo: false

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r/test
        packages:
            - gcc-7
            - g++-7

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - gcc --version
    - g++ --version
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test