language: cpp
dist: trusty
sudo: false

cache: ccache

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libgtest-dev

before_script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cd /usr/src/gtest
    - cmake .
    - make
    - cp *.a /usr/lib

script:
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test
